--!strict
--!native
--!optimize 2
--!nolint LocalShadow
--#selene: allow(shadowing)
-- File generated by Blink v0.18.6 (https://github.com/1Axen/Blink)
-- This file is not meant to be edited

_G._BLINK = _G._BLINK or {}
if _G._BLINK["BLINK"] then
	error("[Blink]: An instance of blink is already running with the remote scope \"BLINK\". Change the remote scope of either instance to avoid conflicts.")
end
_G._BLINK["BLINK"] = true
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

local BASE_EVENT_NAME = "BLINK"
local Invocations = 0

local SendSize = 64
local SendOffset = 0
local SendCursor = 0
local SendBuffer = buffer.create(64)
local SendInstances = {}

local RecieveCursor = 0
local RecieveBuffer = buffer.create(64)

local RecieveInstances = {}
local RecieveInstanceCursor = 0

local Null = newproxy()

type Entry = {
    value: any,
    next: Entry?
}

type Queue = {
    head: Entry?,
    tail: Entry?
}

type BufferSave = {
    Size: number, 
    Cursor: number, 
    Buffer: buffer, 
    Instances: {Instance}
}

local function Read(Bytes: number)
    local Offset = RecieveCursor
    RecieveCursor += Bytes
    return Offset
end

local function Save(): BufferSave
    return {
        Size = SendSize,
        Cursor = SendCursor,
        Buffer = SendBuffer,
        Instances = SendInstances
    }
end

local function Load(Save: BufferSave?)
    if Save then
        SendSize = Save.Size
        SendCursor = Save.Cursor
        SendOffset = Save.Cursor
        SendBuffer = Save.Buffer
        SendInstances = Save.Instances
        return
    end

    SendSize = 64
    SendCursor = 0
    SendOffset = 0
    SendBuffer = buffer.create(64)
    SendInstances = {}
end

local function Invoke()
    if Invocations == 255 then
        Invocations = 0
    end

    local Invocation = Invocations
    Invocations += 1
    return Invocation
end

local function Allocate(Bytes: number)
    local InUse = (SendCursor + Bytes)
    if InUse > SendSize then
        --> Avoid resizing the buffer for every write
        while InUse > SendSize do
            SendSize *= 1.5
        end

        local Buffer = buffer.create(SendSize)
        buffer.copy(Buffer, 0, SendBuffer, 0, SendCursor)
        SendBuffer = Buffer
    end

    SendOffset = SendCursor
    SendCursor += Bytes
    
    return SendOffset
end

local function CreateQueue(): Queue
    return {
        head = nil,
        tail = nil
    }
end

local function Pop(queue: Queue): any
    local head = queue.head
    if head == nil then
        return
    end

    queue.head = head.next
    return head.value
end

local function Push(queue: Queue, value: any)
    local entry: Entry = {
        value = value,
        next = nil
    }

    if queue.tail ~= nil then
        queue.tail.next = entry
    end

    queue.tail = entry

    if queue.head == nil then
        queue.head = entry
    end
end

local Calls = table.create(256)

local Events: any = {
    Reliable = table.create(256),
    Unreliable = table.create(256)
}

local Queue: any = {
    Reliable = table.create(256),
    Unreliable = table.create(256)
}

local SerdesEvent = "?"
local SerdesThread: thread?
Queue.Unreliable[1] = table.create(256)
Queue.Unreliable[2] = table.create(256)
Queue.Unreliable[3] = table.create(256)
export type FireData = { Origin: Vector3, Direction: Vector3, Time: number, ShotIndex: number, LastShootTime: number }
export type Player = Player
export type EquipDatas = { Player: Player, GunInstanceId: number, Equip: boolean }
local function WriteEVENT_ReplicateEquipWeapon(Value: { { Player: Player, GunInstanceId: number, Equip: boolean } }): ()
	-- Allocate BLOCK: 2 bytes
	local BLOCK_START = Allocate(2)
	buffer.writeu8(SendBuffer, BLOCK_START + 0, 0)
	-- START ARRAY
	buffer.writeu8(SendBuffer, BLOCK_START + 1, #Value)
		-- Allocate BLOCK: 3 bytes
	local ARRAY_START_1 = Allocate(3 * #Value)
	for Index = 1, #Value do
		local Item_1 = Value[Index]
		table.insert(SendInstances, Item_1.Player or Null)
		-- Allocate 2
		local OPERATION_OFFSET_0 = ARRAY_START_1
		ARRAY_START_1 += 2
		buffer.writeu16(SendBuffer, OPERATION_OFFSET_0, Item_1.GunInstanceId)
		-- Allocate 1
		local OPERATION_OFFSET_1 = ARRAY_START_1
		ARRAY_START_1 += 1
		buffer.writeu8(SendBuffer, OPERATION_OFFSET_1, Item_1.Equip and 1 or 0)
	end
	-- END ARRAY
end

local function WriteEVENT_FireSound(Value1: number, Value2: Vector3, Value3: Vector3, Value4: number, Value5: number): ()
	-- Allocate BLOCK: 30 bytes
	local BLOCK_START = Allocate(30)
	buffer.writeu8(SendBuffer, BLOCK_START + 0, 0)
	buffer.writeu8(SendBuffer, BLOCK_START + 1, Value1)
	local Vector = Value2
	buffer.writef32(SendBuffer, BLOCK_START + 2, Vector.X)
	buffer.writef32(SendBuffer, BLOCK_START + 6, Vector.Y)
	buffer.writef32(SendBuffer, BLOCK_START + 10, Vector.Z)
	local Vector = Value3
	buffer.writef32(SendBuffer, BLOCK_START + 14, Vector.X)
	buffer.writef32(SendBuffer, BLOCK_START + 18, Vector.Y)
	buffer.writef32(SendBuffer, BLOCK_START + 22, Vector.Z)
	if Value4 > 65504 then
		buffer.writeu16(SendBuffer, BLOCK_START + 26, 0b0_11111_0000000000)
	elseif Value4 < -65504 then
		buffer.writeu16(SendBuffer, BLOCK_START + 26, 0b1_11111_0000000000)
	elseif Value4 ~= Value4 then
		buffer.writeu16(SendBuffer, BLOCK_START + 26, 0b1_11111_0000000001)
	elseif Value4 == 0 then
		buffer.writeu16(SendBuffer, BLOCK_START + 26, 0)
	else
		local float = Value4
		local Abosulte = math.abs(float)
		local Interval = math.ldexp(1, math.floor(math.log(Abosulte, 2)) - 10)
		local RoundedValue = (Abosulte // Interval) * Interval
		local Fraction, Exponent = math.frexp(RoundedValue)
		Exponent += 14
		local Mantissa = math.round(if Exponent <= 0
			then Fraction * 0x400 / math.ldexp(1, math.abs(Exponent))
			else Fraction * 0x800) % 0x400
		local Result = Mantissa
			+ math.max(Exponent, 0) * 0x400
			+ if float < 0 then 0x8000 else 0
		buffer.writeu16(SendBuffer, BLOCK_START + 26, Result)
	end
	buffer.writeu16(SendBuffer, BLOCK_START + 28, Value5)
end

local function ReadEVENT_FireWeapon(): (number, { Origin: Vector3, Direction: Vector3, Time: number, ShotIndex: number, LastShootTime: number })
	-- Read BLOCK: 35 bytes
	local BLOCK_START = Read(35)
	local Value1 = buffer.readu8(RecieveBuffer, BLOCK_START + 0)
	local Value2 = {} :: any
	local X = buffer.readf32(RecieveBuffer, BLOCK_START + 1)
	local Y = buffer.readf32(RecieveBuffer, BLOCK_START + 5)
	local Z = buffer.readf32(RecieveBuffer, BLOCK_START + 9)
	Value2.Origin = Vector3.new(X, Y, Z)
	X = buffer.readf32(RecieveBuffer, BLOCK_START + 13)
	Y = buffer.readf32(RecieveBuffer, BLOCK_START + 17)
	Z = buffer.readf32(RecieveBuffer, BLOCK_START + 21)
	Value2.Direction = Vector3.new(X, Y, Z)
	Value2.Time = buffer.readf32(RecieveBuffer, BLOCK_START + 25)
	Value2.ShotIndex = buffer.readu16(RecieveBuffer, BLOCK_START + 29)
	Value2.LastShootTime = buffer.readf32(RecieveBuffer, BLOCK_START + 31)
	return Value1, Value2
end

local function ReadEVENT_ReloadWeapon(): (number)
	-- Read BLOCK: 1 bytes
	local BLOCK_START = Read(1)
	local Value = buffer.readu8(RecieveBuffer, BLOCK_START + 0)
	return Value
end

local function WriteEVENT_SyncEventState(Value1: number, Value2: number, Value3: number): ()
	-- Allocate BLOCK: 5 bytes
	local BLOCK_START = Allocate(5)
	buffer.writeu8(SendBuffer, BLOCK_START + 0, 1)
	buffer.writeu8(SendBuffer, BLOCK_START + 1, Value1)
	buffer.writeu8(SendBuffer, BLOCK_START + 2, Value2)
	buffer.writeu16(SendBuffer, BLOCK_START + 3, Value3)
end

local function WriteEVENT_RegisterWeapon(Value1: number): ()
	-- Allocate BLOCK: 3 bytes
	local BLOCK_START = Allocate(3)
	buffer.writeu8(SendBuffer, BLOCK_START + 0, 2)
	buffer.writeu16(SendBuffer, BLOCK_START + 1, Value1)
end

local function ReadEVENT_ChangeStateWeapon(): (number, number, boolean)
	-- Read BLOCK: 3 bytes
	local BLOCK_START = Read(3)
	local Value1 = buffer.readu8(RecieveBuffer, BLOCK_START + 0)
	local Value2 = buffer.readu8(RecieveBuffer, BLOCK_START + 1)
	local Value3 = (buffer.readu8(RecieveBuffer, BLOCK_START + 2) == 1)
	return Value1, Value2, Value3
end

if not RunService:IsRunning() then
	local NOOP = function() end
	local Returns = table.freeze({
	ReplicateEquipWeapon = {
		Fire = NOOP,
		FireAll = NOOP,
		FireList = NOOP,
		FireExcept = NOOP
	},
	FireSound = {
		Fire = NOOP,
		FireAll = NOOP,
		FireList = NOOP,
		FireExcept = NOOP
	},
	FireWeapon = {
		On = NOOP
	},
	ReloadWeapon = {
		On = NOOP
	},
	SyncEventState = {
		Fire = NOOP,
		FireAll = NOOP,
		FireList = NOOP,
		FireExcept = NOOP
	},
	RegisterWeapon = {
		Fire = NOOP,
		FireAll = NOOP,
		FireList = NOOP,
		FireExcept = NOOP
	},
	ChangeStateWeapon = {
		On = NOOP
	},
	})
	return Returns :: BLINK_EVENTS_SYMBOL
end

if not RunService:IsServer() then
    error("Server network module can only be required from the server.")
end

local Reliable: RemoteEvent = ReplicatedStorage:FindFirstChild(BASE_EVENT_NAME .. "_RELIABLE_REMOTE") :: RemoteEvent
if not Reliable then
    local RemoteEvent = Instance.new("RemoteEvent")
    RemoteEvent.Name = BASE_EVENT_NAME .. "_RELIABLE_REMOTE"
    RemoteEvent.Parent = ReplicatedStorage
    Reliable = RemoteEvent
end

local Unreliable: UnreliableRemoteEvent = ReplicatedStorage:FindFirstChild(BASE_EVENT_NAME .. "_UNRELIABLE_REMOTE") :: UnreliableRemoteEvent
if not Unreliable then
    local UnreliableRemoteEvent = Instance.new("UnreliableRemoteEvent")
    UnreliableRemoteEvent.Name = BASE_EVENT_NAME .. "_UNRELIABLE_REMOTE"
    UnreliableRemoteEvent.Parent = ReplicatedStorage
    Unreliable = UnreliableRemoteEvent
end

local PlayersMap: {[Player]: BufferSave} = {}

Players.PlayerRemoving:Connect(function(Player)
    PlayersMap[Player] = nil
end)

local function StepReplication()
    for Player, Send in PlayersMap do
        if Send.Cursor <= 0 then
            continue
        end

        local Buffer = buffer.create(Send.Cursor)
        buffer.copy(Buffer, 0, Send.Buffer, 0, Send.Cursor)
        Reliable:FireClient(Player, Buffer, Send.Instances)

        Send.Size = 64
        Send.Cursor = 0
        Send.Buffer = buffer.create(64)
        table.clear(Send.Instances)
    end
end
RunService.Heartbeat:Connect(StepReplication)
Reliable.OnServerEvent:Connect(function(Player: Player, Buffer: buffer, Instances: {Instance})
	RecieveCursor = 0
	RecieveBuffer = Buffer
	RecieveInstances = Instances
	RecieveInstanceCursor = 0
	local Size = buffer.len(RecieveBuffer)
	if SerdesThread and coroutine.status(SerdesThread) == "suspended" then
		warn(`[Blink]: Yielded in a Sync call. Event "{SerdesEvent}" uses a Sync call, consider using an Async call instead.`)
		coroutine.close(SerdesThread)
	end
	SerdesThread = coroutine.running()
	while (RecieveCursor < Size) do
		-- Read BLOCK: 1 bytes
		local BLOCK_START = Read(1)
		local Index = buffer.readu8(RecieveBuffer, BLOCK_START + 0)
	end
end)
Unreliable.OnServerEvent:Connect(function(Player: Player, Buffer: buffer, Instances: {Instance})
	RecieveCursor = 0
	RecieveBuffer = Buffer
	RecieveInstances = Instances
	RecieveInstanceCursor = 0
	local Size = buffer.len(RecieveBuffer)
	if SerdesThread and coroutine.status(SerdesThread) == "suspended" then
		warn(`[Blink]: Yielded in a Sync call. Event "{SerdesEvent}" uses a Sync call, consider using an Async call instead.`)
		coroutine.close(SerdesThread)
	end
	SerdesThread = coroutine.running()
	while (RecieveCursor < Size) do
		-- Read BLOCK: 1 bytes
		local BLOCK_START = Read(1)
		local Index = buffer.readu8(RecieveBuffer, BLOCK_START + 0)
		if Index == 1 then
			local Value1: number, Value2: { Origin: Vector3, Direction: Vector3, Time: number, ShotIndex: number, LastShootTime: number } = ReadEVENT_FireWeapon()
			if Events.Unreliable[1] ~= nil then
				task.spawn(Events.Unreliable[1], Player, Value1, Value2)
			end
		elseif Index == 2 then
			local Value: number = ReadEVENT_ReloadWeapon()
			if Events.Unreliable[2] ~= nil then
				task.spawn(Events.Unreliable[2], Player, Value)
			end
		elseif Index == 3 then
			local Value1: number, Value2: number, Value3: boolean = ReadEVENT_ChangeStateWeapon()
			if Events.Unreliable[3] ~= nil then
				task.spawn(Events.Unreliable[3], Player, Value1, Value2, Value3)
			end
		end
	end
end)


local Returns = table.freeze({
	StepReplication = StepReplication,

	ReplicateEquipWeapon = {
		Fire = function(Player: Player, Value: { { Player: Player, GunInstanceId: number, Equip: boolean } }): ()
			Load(PlayersMap[Player])
			WriteEVENT_ReplicateEquipWeapon(Value)
			PlayersMap[Player] = Save()
		end,
		FireAll = function(Value: { { Player: Player, GunInstanceId: number, Equip: boolean } }): ()
			Load()
			WriteEVENT_ReplicateEquipWeapon(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireList = function(List: {Player}, Value: { { Player: Player, GunInstanceId: number, Equip: boolean } }): ()
			Load()
			WriteEVENT_ReplicateEquipWeapon(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in List do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireExcept = function(Except: Player, Value: { { Player: Player, GunInstanceId: number, Equip: boolean } }): ()
			Load()
			WriteEVENT_ReplicateEquipWeapon(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				if Player == Except then
					continue
				end
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
	},
	FireSound = {
		Fire = function(Player: Player, Value1: number, Value2: Vector3, Value3: Vector3, Value4: number, Value5: number): ()
			Load()
			WriteEVENT_FireSound(Value1, Value2, Value3, Value4, Value5)
			local Buffer = buffer.create(SendCursor)
			buffer.copy(Buffer, 0, SendBuffer, 0, SendCursor)
			Unreliable:FireClient(Player, Buffer, SendInstances)
		end,
		FireAll = function(Value1: number, Value2: Vector3, Value3: Vector3, Value4: number, Value5: number): ()
			Load()
			WriteEVENT_FireSound(Value1, Value2, Value3, Value4, Value5)
			local Buffer = buffer.create(SendCursor)
			buffer.copy(Buffer, 0, SendBuffer, 0, SendCursor)
			Unreliable:FireAllClients(Buffer, SendInstances)
		end,
		FireList = function(List: {Player}, Value1: number, Value2: Vector3, Value3: Vector3, Value4: number, Value5: number): ()
			Load()
			WriteEVENT_FireSound(Value1, Value2, Value3, Value4, Value5)
			local Buffer = buffer.create(SendCursor)
			buffer.copy(Buffer, 0, SendBuffer, 0, SendCursor)
			for _, Player in List do
				Unreliable:FireClient(Player, Buffer, SendInstances)
			end
		end,
		FireExcept = function(Except: Player, Value1: number, Value2: Vector3, Value3: Vector3, Value4: number, Value5: number): ()
			Load()
			WriteEVENT_FireSound(Value1, Value2, Value3, Value4, Value5)
			local Buffer = buffer.create(SendCursor)
			buffer.copy(Buffer, 0, SendBuffer, 0, SendCursor)
			for _, Player in Players:GetPlayers() do
				if Player == Except then
					continue
				end
				Unreliable:FireClient(Player, Buffer, SendInstances)
			end
		end,
	},
	FireWeapon = {
		On = function(Listener: (Player: Player, Value1: number, Value2: { Origin: Vector3, Direction: Vector3, Time: number, ShotIndex: number, LastShootTime: number }) -> ()): () -> ()
			Events.Unreliable[1] = Listener
			return function (): ()
				if Events.Unreliable[1] == Listener then
					Events.Unreliable[1] = nil
				end
			end
		end
	},
	ReloadWeapon = {
		On = function(Listener: (Player: Player, Value: number) -> ()): () -> ()
			Events.Unreliable[2] = Listener
			return function (): ()
				if Events.Unreliable[2] == Listener then
					Events.Unreliable[2] = nil
				end
			end
		end
	},
	SyncEventState = {
		Fire = function(Player: Player, Value1: number, Value2: number, Value3: number): ()
			Load(PlayersMap[Player])
			WriteEVENT_SyncEventState(Value1, Value2, Value3)
			PlayersMap[Player] = Save()
		end,
		FireAll = function(Value1: number, Value2: number, Value3: number): ()
			Load()
			WriteEVENT_SyncEventState(Value1, Value2, Value3)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireList = function(List: {Player}, Value1: number, Value2: number, Value3: number): ()
			Load()
			WriteEVENT_SyncEventState(Value1, Value2, Value3)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in List do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireExcept = function(Except: Player, Value1: number, Value2: number, Value3: number): ()
			Load()
			WriteEVENT_SyncEventState(Value1, Value2, Value3)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				if Player == Except then
					continue
				end
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
	},
	RegisterWeapon = {
		Fire = function(Player: Player, Value1: number): ()
			Load(PlayersMap[Player])
			WriteEVENT_RegisterWeapon(Value1)
			PlayersMap[Player] = Save()
		end,
		FireAll = function(Value1: number): ()
			Load()
			WriteEVENT_RegisterWeapon(Value1)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireList = function(List: {Player}, Value1: number): ()
			Load()
			WriteEVENT_RegisterWeapon(Value1)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in List do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireExcept = function(Except: Player, Value1: number): ()
			Load()
			WriteEVENT_RegisterWeapon(Value1)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				if Player == Except then
					continue
				end
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
	},
	ChangeStateWeapon = {
		On = function(Listener: (Player: Player, Value1: number, Value2: number, Value3: boolean) -> ()): () -> ()
			Events.Unreliable[3] = Listener
			return function (): ()
				if Events.Unreliable[3] == Listener then
					Events.Unreliable[3] = nil
				end
			end
		end
	},
})
type BLINK_EVENTS_SYMBOL = typeof(Returns)
return Returns :: BLINK_EVENTS_SYMBOL