local ProceduralSway = require(script.ProceduralSway)
local MouseSway = require(script.MouseSway)
local RotationalSway = require(script.RotationalSway)
local WalkTilt = require(script.WalkTilt)
local CameraRecoil = require(script.CameraRecoil)
local WeaponRecoil = require(script.WeaponRecoil)
local SprintTilt = require(script.SprintTilt)
local WalkBob = require(script.WalkBob)
local SpringSway = require(script.SpringSway)

return {
	ProceduralSway = ProceduralSway,
	MouseSway = MouseSway,
	RotationalSway = RotationalSway,
	WalkTilt = WalkTilt,
	CameraRecoil = CameraRecoil,
	WeaponRecoil = WeaponRecoil,
	SprintTilt = SprintTilt,
	WalkBob = WalkBob,
	SpringSway = SpringSway,
}